server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
#    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.105.37.164:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 116924
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 2726066523@qq.com
  redis:
    database: 0
    host: 39.105.37.164
    port: 6379
    password: 116924
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: 39.105.37.164
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: 116924

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emoswx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emoswx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"

emos:
  jwt:
    #秘钥
    secret: 116924
    #过期时间（天）
    expire: 5
    #缓存过期时间（天）
    cache-expire: 10
  face:
    createFaceModelUrl: http://192.168.8.114:3000/create_face_model
    checkinUrl: http://192.168.8.114:3000/checkin
  email:
    system: 2726066523@qq.com
    zzy: nextoayou@163.com
  image-folder: D:/emos/image

wx:
  app-id: wx8dc396836c538a99
  app-secret: 43df8a274a82cd0c8d2c58dc104d09ba



